[package]
name = "wasm-tools"
version = "0.1.0"
authors = ["The Wasmtime Project Developers"]
edition = "2018"
publish = false

[workspace]

[dependencies]
anyhow = "1.0"
getopts = "0.2"
wasmparser = { path = "crates/wasmparser" }
wasmprinter = { path = "crates/wasmprinter" }
wat = { path = "crates/wat" }
