[package]
name = "wast"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[workspace]
members = ['fuzz']

[dependencies]
leb128 = "0.2"

[dev-dependencies]
rayon = "1.0"
