[package]
name = "wast"
version = "1.0.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[workspace]
members = ['fuzz']

[dependencies]
wast-parser = { path = 'crates/parser', version = '0.1.0' }

[dev-dependencies]
anyhow = "*"
getopts = "*"
rayon = "1.0"
serde_json = "1.0"
tempfile = "3.1"
wasmparser = "0.39"

[profile.release]
debug-assertions = true
overflow-checks = true

[[test]]
name = "wabt"
harness = false
