[package]
name = "wasm-tools"
version = "0.1.0"
authors = ["The Wasmtime Project Developers"]
edition = "2018"
publish = false

[workspace]
members = ['fuzz', 'crates/wasm-encoder', 'crates/fuzz-stats', 'crates/wasm-mutate-stats']

[dependencies]
anyhow = "1.0"
arbitrary = "1.0.0"
env_logger = "0.8"
flagset = "0.4"
getopts = "0.2"
is_executable = "1.0.1"
log = "0.4"
rayon = "1.0"
structopt = "0.3.16"
tempfile = "3.2.0"
wasm-mutate = { path = "crates/wasm-mutate", features = ["structopt"] }
wasm-shrink = { path = "crates/wasm-shrink", features = ["structopt"] }
wasm-smith = { path = "crates/wasm-smith", features = ["_internal_cli"] }
wasmparser = { path = "crates/wasmparser" }
wasmparser-dump = { path = "crates/dump" }
wasmprinter = { path = "crates/wasmprinter" }
wast = { path = "crates/wast" }
wat = { path = "crates/wat" }
serde_json = "1"
serde = { version = "1", features = ['derive'] }

[dev-dependencies]
anyhow = "1.0"
getopts = "0.2"
serde_json = "1.0"
tempfile = "3.1"
diff = "0.1"
wasmparser-dump = { path = 'crates/dump' }

[[test]]
name = "dump"
harness = false

[[test]]
name = "roundtrip"
harness = false
