[package]
name = "wast"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[workspace]
members = ['fuzz']

[dependencies]
hexf-parse = "0.1"
leb128 = "0.2"

[dev-dependencies]
rayon = "1.0"
anyhow = "1.0"
tempfile = "3.1"
wasmparser = "0.39"
serde_json = "1.0"

[profile.release]
debug-assertions = true
overflow-checks = true
