[package]
name = "wasmparser"
version = "0.4.1"
authors = ["Yury Delendik <ydelendik@mozilla.com>"]
license = "Apache-2.0"
repository = "https://github.com/yurydelendik/wasmparser.rs"
description = """
wasmparser in Rust.
"""

[dependencies]
