[package]
name = "wasmprinter"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
repository = "https://github.com/bytecodealliance/wasmprinter"
homepage = "https://github.com/bytecodealliance/wasmprinter"
documentation = "https://docs.rs/wasmprinter"
description = """
Rust converter from the WebAssembly binary format to the text format.
"""
exclude = ['tests/wabt']

[workspace]
members = ['fuzz']

[dependencies]
anyhow = "1.0"
wasmparser = { git = 'https://github.com/alexcrichton/wasmparser.rs', branch = 'updates' }

[dev-dependencies]
rayon = "1.0"
tempfile = "3.0"
wast = "3.0.3"
wat = "1.0.4"
diff = "0.1"

[[test]]
name = "wabt"
harness = false

[profile.release]
debug-assertions = true
overflow-checks = true
