[package]
name = "wit-parser"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.3.0"
edition.workspace = true

[dependencies]
id-arena = "2"
anyhow = { workspace = true }
indexmap = { workspace = true }
pulldown-cmark = { version = "0.8", default-features = false }
unicode-xid = "0.2.2"

[dev-dependencies]
rayon = "1"
serde_json = "1"
serde = { version = "1", features = ['derive'] }

[[test]]
name = "all"
harness = false
