[package]
name = "wat"
version = "1.0.18"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "Apache-2.0 WITH LLVM-exception"
readme = "README.md"
repository = "https://github.com/bytecodealliance/wasm-tools/tree/master/crates/wat"
homepage = "https://github.com/bytecodealliance/wasm-tools/tree/master/crates/wat"
documentation = "https://docs.rs/wat"
description = """
Rust parser for the WebAssembly Text format, WAT
"""

[dependencies]
wast = { path = '../wast', version = '17.0.0' }

[dev-dependencies]
anyhow = "1.0"
getopts = "0.2"
rayon = "1.0"
serde_json = "1.0"
tempfile = "3.1"
wasmparser = { path = '../wasmparser' }
diff = "0.1"
