[package]
name = "wast-fuzz"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0"
getrandom = "0.1"
tempfile = "3"
wasmparser = { path = "../wasmparser" }
wast = { path = "../wast" }
wat = { path = "../wat" }
