[package]
name = "wast"
version = "2.0.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/alexcrichton/wat/tree/master/crates/wast"
homepage = "https://github.com/alexcrichton/wat/tree/master/crates/wast"
documentation = "https://docs.rs/wast"
description = """
Customizable Rust parsers for the WebAssembly Text formats WAT and WAST
"""

[dependencies]
leb128 = "0.2"

[dev-dependencies]
rayon = "1.0"
anyhow = "1.0"
tempfile = "3.1"
wasmparser = "0.39"
serde_json = "1.0"
