[package]
name = "wast-fuzz"
version = "0.0.1"
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
wast = { path = ".." }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys" }

[[bin]]
name = "lexer"
path = "fuzz_targets/lexer.rs"

[[bin]]
name = "parser"
path = "fuzz_targets/parser.rs"

[[bin]]
name = "binary"
path = "fuzz_targets/binary.rs"
