[package]
name = "wast-libfuzzer"
version = "0.0.1"
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
wat = { path = ".." }
wast = { path = "../crates/wast" }
wast-fuzz = { path = "../crates/wast-fuzz" }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys" }
tempfile = "3.0"
wasmparser = "0.32"

[[bin]]
name = "lexer"
path = "fuzz_targets/lexer.rs"

[[bin]]
name = "parser"
path = "fuzz_targets/parser.rs"

[[bin]]
name = "binary"
path = "fuzz_targets/binary.rs"
