[package]
name = "wast-libfuzzer"
version = "0.0.1"
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
wasmprinter = { path = ".." }
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys" }

[[bin]]
name = "print"
path = "fuzz_targets/print.rs"
